name: Workflow which downloads Readme file

env:
  ENV_PATH: 'README.md'
on: push
jobs:
  # job name
  upload-artifact:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      # Step 1 Checks-out your repository
      - name: Checkout
        uses: actions/checkout@v4

      # Spep2 - access env vars from shell
      - name: Run a one-line script
        run: echo $Env:ENV_PATH

      # Step - 3 create artifact
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ENV_PATH}}
          path: ./${{env.ENV_PATH}}
      

