name: Run js Hello World

on: push

jobs:
  run-script:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: node Hello.js

  create-artifact:
    needs: run-script
    runs-on: windows-latest
    steps:
      # Step 1 Checks-out your repository
      - name: Checkout
        uses: actions/checkout@v4
      # Step 2 create artifact
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: arifacts
          path: .

